import type { Metadata } from "next";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "@/contexts/session-context";
import { QueryProvider } from "@/lib/query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" suppressHydrationWarning>
        <QueryProvider>
          <SessionProvider>{children}</SessionProvider>
          <Toaster />
        </QueryProvider>
      </body>
    </html>
  );
}
